### ISSUE TITLE
Not working on vscode 1.31.0

### ISSUE THREAD

**Issue by oldtimerza** [VSCodeVim/Vim#3473]
VSCodeVim version 1.0.8 stopped working entirely on VSCode version 1.31.0 for me.

1.  Install VsCode version 1.31.0
2.  Install VSCodeVim version 1.0.8
3.  Vim no longer works.
4.  Change install to VSCodeVim 1.0.7 and it starts working again.

- Extension (VsCodeVim) version: 1.0.8
- VSCode version: 1.31.0
- OS: Windows 10

Additional info: 
using ctrl+shift+P to run vim: Toggle Vim Mode gives an error with "Commamd toggleVim not found"

**Comment by sparky005** [comment]
Same issue. Also win10, also latest vscode, also latest vim extension. Downgrading to vim extension 1.0.7 also fixes for me.

**Comment by esimakin** [comment]
Hi guys,
I'm observing the same issue.
* Extension (VsCodeVim) version: 1.0.8
* VSCode version: 1.31.0
* OS: Windows 10

Here is some helpful info from DevTools:
``` extensionService.ts:800 Activating extension 'vscodevim.vim' failed: Cannot find module 'winston-transport'.
t._logMessageInConsole @ extensionService.ts:800

[Extension Host] Activating extension 'vscodevim.vim' failed: Cannot find module 'winston-transport'.
t.log @ console.ts:134

Error: Cannot find module 'winston-transport'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
	at Function.Module._load (internal/modules/cjs/loader.js:528:25)
	at Function.t._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:751:268)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:730:770)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:674:774)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (C:\Users\Evgenii_Simakin\.vscode\extensions\vscodevim.vim-1.0.8\out\src\util\logger.js:11:25)
	at Object.<anonymous> (C:\Users\Evgenii_Simakin\.vscode\extensions\vscodevim.vim-1.0.8\out\src\util\logger.js:84:3)
	at Module.t._initNodeRequire.r._compile (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:751:268)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:730:770)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:674:774)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (C:\Users\Evgenii_Simakin\.vscode\extensions\vscodevim.vim-1.0.8\out\src\mode\modes.js:3:18)
	at Object.<anonymous> (C:\Users\Evgenii_Simakin\.vscode\extensions\vscodevim.vim-1.0.8\out\src\mode\modes.js:139:3)
	at Module.t._initNodeRequire.r._compile (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:751:268)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:730:770)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:674:774)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (C:\Users\Evgenii_Simakin\.vscode\extensions\vscodevim.vim-1.0.8\out\src\common\motion\position.js:6:17)
	at Object.<anonymous> (C:\Users\Evgenii_Simakin\.vscode\extensions\vscodevim.vim-1.0.8\out\src\common\motion\position.js:898:3)
	at Module.t._initNodeRequire.r._compile (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:751:268)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:730:770)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:674:774)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (C:\Users\Evgenii_Simakin\.vscode\extensions\vscodevim.vim-1.0.8\out\src\actions\operator.js:20:20)
	at Object.<anonymous> (C:\Users\Evgenii_Simakin\.vscode\extensions\vscodevim.vim-1.0.8\out\src\actions\operator.js:993:3)
	at Module.t._initNodeRequire.r._compile (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:751:268)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:730:770)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:674:774)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (C:\Users\Evgenii_Simakin\.vscode\extensions\vscodevim.vim-1.0.8\out\src\actions\include-all.js:4:1)
	at Object.<anonymous> (C:\Users\Evgenii_Simakin\.vscode\extensions\vscodevim.vim-1.0.8\out\src\actions\include-all.js:18:3)
	at Module.t._initNodeRequire.r._compile (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:751:268)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:730:770)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:674:774)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (C:\Users\Evgenii_Simakin\.vscode\extensions\vscodevim.vim-1.0.8\out\extension.js:16:1)
	at Object.<anonymous> (C:\Users\Evgenii_Simakin\.vscode\extensions\vscodevim.vim-1.0.8\out\extension.js:373:3)
	at Module.t._initNodeRequire.r._compile (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:751:268)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:730:770)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:674:774)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.i [as __$__nodeRequire] (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:31:542)
	at c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:740:5
	at t._doActivateExtension (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:740:113)
	at t._activateExtension (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:738:785)
	at Object.actualActivateExtension (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:735:633)
	at e._activateExtension (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:330:969)
	at c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:330:592
	at Array.map (<anonymous>)
	at e._activateExtensions (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:330:567)
	at e.activateByEvent (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:328:462)
	at t._activateByEvent (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:737:174)
	at t._handleEagerExtensions (c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:741:590)
	at c:\Users\Evgenii_Simakin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:745:298
	at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by troyibm** [comment]
'dd' has weird behavior for me since upgrading to VSCode 1.31.0.  It deletes the line, but then moves the cursor to the bottom of the file with input mode active so a subsequent 'dd' will delete the last line and so on.

**Comment by jpoon** [comment]
Such errors:

```
[Extension Host] Activating extension 'vscodevim.vim' failed: Cannot find module 'XYZ'.
```

indicate that the installation of the extension failed. The remedy is to:

1) delete the .vscodevim folder (~/.vscode/extensions/vscodevim)
2) re-installing vscodevim

This was the upstream issue that was supposedly fixed: https://github.com/Microsoft/vscode/issues/43813

Similar issues:
https://github.com/VSCodeVim/Vim/issues/2287, https://github.com/VSCodeVim/Vim/issues/2185, https://github.com/VSCodeVim/Vim/issues/2436
