### ISSUE TITLE
vim extentions does not work, "Cannot find module './../actions/commands/actions'"

### ISSUE THREAD

**Issue by FrankKirin** [VSCodeVim/Vim#4343]
**Describe the bug**
The vscodevim extention can not work in vs code 1.40.2 version

**To Reproduce**

1.  Update vs code to version: 1.40.2
2.  Install the vscodevim extension, version: 1.12.0

**Screenshots**
![11575882387_ pic_hd](https://user-images.githubusercontent.com/23259946/70429705-1c552900-1ab4-11ea-81fc-699c94bad265.jpg)

**Environment (please complete the following information):**

Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by philippmayrth** [comment]
I have the same issue on a Mac but only with Vim plugin version 1.12.0 older versions work fine.

VSCode info:
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

**Comment by sb-junhyeong** [comment]
1.2.0 Seems to be broken, Older versions would work fine.

**Comment by dkms-its** [comment]
Is there a way to downgrade temporarily? I feel like having my hands hacked off without the vim keybindings :)

**Comment by tephe** [comment]
Same issue for me, using the previous version works.

**Comment by BasBuller** [comment]
I have the same issue with 1.12.0 on ubuntu 19.04, older versions work fine.

**Comment by cd1m0** [comment]
Same issue Ubuntu 18.10 VSCode 1.40.2

**Comment by dkms-its** [comment]
Guys, subscribing to this issue is enough, there's no point "me too"-ing.

**Comment by cakecatz** [comment]
https://github.com/VSCodeVim/Vim/releases/tag/v1.12.0
This page's exntesion includes `actions/commands/actions.js`, so it works.

But [extension page's](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) extension not includes `actions/commands/actions.js`.

**Comment by rebornix** [comment]
Fixed in 1.12.1, sorry for the trouble.

**Comment by pho3nixf1re** [comment]
Thank you so much for the quick turn around. 🏅

**Comment by rebornix** [comment]
There are still some issues ppl are seeing now, let's track it in https://github.com/VSCodeVim/Vim/issues/4342#issuecomment-563338094.
