### ISSUE TITLE
1.22 broken for browser

### ISSUE THREAD

**Issue by gengjiawen** [VSCodeVim/Vim#7469]
**Describe the bug**
Can't be activated

**To Reproduce**
https://github.com/gengjiawen/gitpod-vim

click the badge in `README`

**Expected behavior**

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.22.1	
- VSCode version: 1.64.0
- OS: Linux

**Additional context**

1.21 works, looks like an regression.

**Comment by filiptronicek** [comment]
I can reproduce in vscode.dev, so this is not only applicable to Gitpod.

<details>
<summary>Logs from vscode.dev</summary>

```
[2022-02-09 12:05:32.548] [exthost] [error] Activating extension vscodevim.vim failed due to an error:
[2022-02-09 12:05:32.549] [exthost] [error] ./src/util/externalCommand.ts/o<@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:543468
./src/util/externalCommand.ts@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:543558
r@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:612402
./src/cmd_line/commands/bang.ts@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:337068
r@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:612402
./src/vimscript/exCommandParser.ts@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:549445
r@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:612402
./src/cmd_line/commandLine.ts@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:328402
r@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:612402
./src/actions/commands/actions.ts@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:138342
r@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:612402
./src/register/register.ts@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:487731
r@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:612402
./src/actions/operator.ts@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:295039
r@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:612402
./src/actions/include-main.ts@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:254108
r@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:612402
anonymous/</</<@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:612780
anonymous/</<@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:613074
anonymous/<@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:613080
anonymous/<@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:84
anonymous@https://vscodevim.vscode-unpkg.net/vscodevim/vim/1.22.1/extension/out/extensionWeb.js#vscode-extension:4:223
_loadCommonJSModule@../../../vs/workbench/api/worker/extensionHostWorker.js:79:603

```

</details>

**Comment by filiptronicek** [comment]
This is a regression from https://github.com/VSCodeVim/Vim/pull/7252, because it adds an import for https://github.com/VSCodeVim/Vim/blob/master/src/util/child_process.ts, which leverages the [Node `child_process` API](https://nodejs.org/api/child_process.html), which fails to load, since its run in a browser context, not a Node one. This wasn't a problem before since although the script also tried importing this API, it just threw an exception caught by a `try catch` block. https://github.com/VSCodeVim/Vim/blob/94503c480eb69e638249600ead655600040051b8/src/util/externalCommand.ts#L99-L106

**Comment by filiptronicek** [comment]
There's another error we found, introduced in https://github.com/VSCodeVim/Vim/pull/7360, which tries to load in https://github.com/VSCodeVim/Vim/blob/master/src/configuration/vimrc.ts. This file is noto accessible via Webpack so it just throws an error that the module couldn't be found. 

```
'Activating extension 'vscodevim.vim' failed: Cannot find module '[./src/configuration/vimrc]()'.'
```

**Comment by J-Fields** [comment]
Thanks for the analysis, @filiptronicek! If anyone wants to take a stab at fixing this, PRs are welcome; otherwise I'll try to get to it later today.

**Comment by filiptronicek** [comment]
@J-Fields we tried with @jeanp413 today and the first issue is fixed by https://github.com/filiptronicek/Vim/commit/5d4f9d6b6b735078ea63894480290422eea7ef4e, but sadly we didn't have bandwidth to tackle the second issue today, just analysis.

**Comment by Craftidore** [comment]
It appears to work fine in version 1.22.0, just not 1.22.1
<img width="571" alt="image" src="https://user-images.githubusercontent.com/73705352/153761264-6e11bbaf-9e06-4c83-a4ac-934897a4b9a1.png">

**Comment by fiveable-jferg** [comment]
Gitpod user here - I was able to work around this yesterday by just downgrading to 1.21.10, but today it's showing up as:  

![image](https://user-images.githubusercontent.com/88333913/154360515-c0170028-4916-488a-9e7c-1c6d540095b9.png)

which means I'm basically going to have to fall back to setting up a local VS code instance.  Any suggestions on what changed between yesterday and today?  @filiptronicek , any word on https://github.com/filiptronicek/Vim/commit/5d4f9d6b6b735078ea63894480290422eea7ef4e getting merged in?  (Is there a PR for it?)

**Comment by bcho** [comment]
> ~It appears to work fine in version 1.22.0, just not 1.22.1~
> 
> EDIT: Tested again, and it doesn't work on 1.22.0.

Hey, this is because the fix is not being released yet. @J-Fields any chance to release a new patch version to fix this issue?

**Comment by jeanp413** [comment]
Hey @J-Fields, @mustard-mh and me created a PR fixing this https://github.com/VSCodeVim/Vim/pull/7520 could you review :pray:

**Comment by Craftidore** [comment]
I can confirm this works in github.dev codespaces.

**Comment by medihack** [comment]
And also works with v1.22.2 in Gitpod again .... hooray and a big thank you!

**Comment by akosyakov** [comment]
here is an issue to prevent such breakage: https://github.com/VSCodeVim/Vim/issues/7530 please upvote 🙏

**Comment by gengjiawen** [comment]
> here is an issue to prevent such breakage: #7530 please upvote 🙏

Thanks for raising this. I was plan to create a similar issue but too busy. Great work !
